global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nifi'
    metrics_path: '/metrics/'
    fallback_scrape_protocol: PrometheusText1.0.0
    static_configs:
      - targets: ['nifi:9092']

